language: generic

os:
- linux
- osx

sudo: required

before_install:
- echo $LD_LIBRARY_PATH
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib:/usr/lib
# install libbsd on linux
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libbsd-dev; fi
- ls /lib
# install libarchive
- wget https://github.com/libarchive/libarchive/archive/v3.3.1.tar.gz
- tar xzvf v3.3.1.tar.gz
- cd libarchive-3.3.1 && build/autogen.sh && ./configure && make && sudo make install
# install pkg
- git clone https://github.com/freebsd/pkg.git
- cd pkg && ./autogen.sh && ./configure && make && sudo make install
# install atom
- sudo make install
script: make test
