language: generic

os:
- linux
- osx

sudo: required

before_install:
- wget https://github.com/libarchive/libarchive/archive/v3.3.1.tar.gz
- tar xzf libarchive-3.3.1.tar.gz
- cd libarchive-3.3.1 && ./configure && make && sudo make install
- git clone https://github.com/freebsd/pkg.git
- cd pkg && ./autogen.sh && ./configure && make && sudo make install
- sudo make install
script: make test