language: generic

os:
- osx
- linux

sudo: required

before_install:
# install libarchive on osx
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libarchive; fi
# install libarchive on linux
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libbsd0 libarchive13; fi
# install pkg
- git clone https://github.com/freebsd/pkg.git
- cd pkg && ./autogen.sh && ./configure && make && sudo make install
# install atom
- sudo make install
script: make test